### ISSUE TITLE
Need d.ts file for Targeting the angular beta

### ISSUE THREAD

**Issue by vijayaragavendiran** [WebReflection/JSONH#14]
@WebReflection I am targeting for angular beta project. I need d.ts file for JSONH to import in the angular component. Please help me.

#Thanks
Vijay

**Comment by WebReflection** [comment]
I'm afraid you rather have a problem with your framework, not with JSONH which is plain x-platform JavaScript.

If angular doesn't accept JS, change framework or please complain in there.
