### ISSUE TITLE
uncompress file with JS

### ISSUE THREAD

**Issue by isaacSolano** [WebReflection/JSONH#17]
Basically I have to use this tool to uncompress a JSON file and get the original JSON format, any idea of how I can do that? I'm using JS btw... thanks for the answers !

**Comment by WebReflection** [comment]
As explained in here:
https://github.com/WebReflection/JSONH#jsonh-api

```js
const object = JSONH.parse(fileContent);
```

**Comment by isaacSolano** [comment]
and what dependencie should I install for node?

**Comment by WebReflection** [comment]
`npm i jsonh`

**Comment by isaacSolano** [comment]
Thanks for your answers but still when I tried to uncompress the file it comes as empty array, this is the way I'm trying

![image](https://user-images.githubusercontent.com/35480414/71599551-e8987c80-2b10-11ea-93e4-70c3d24ba82b.png)

**Comment by WebReflection** [comment]
Without knowing the content of the file there's nothing I can do.

**Comment by isaacSolano** [comment]
Yeeaah basically is a simple object that was compressed using this library, to give you an idea looks like this

![image](https://user-images.githubusercontent.com/35480414/71622696-3ce93e00-2b9d-11ea-9ea6-5fc8816c82e1.png)

**Comment by WebReflection** [comment]
So, only `e` should be unpacked, not the whole thing.

**Comment by isaacSolano** [comment]
Thanks for your answer

But still when i try to apply the jsonh.parse on the `e` property of the
object it gives the same error

[image: image.png]

**Comment by WebReflection** [comment]
So either you give me a proper sample or you gotta figure out yourself, sorry

**Comment by isaacSolano** [comment]
Yeah I already did, now you figure out the problem I had to avoid more
confusion from other people with that "tool"

**Comment by WebReflection** [comment]
The tool works as described and I'm closing this badly filed issue.

https://medium.com/@WebReflection/how-to-file-a-github-lab-issue-7080b8c0cef5
